# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

linter:
  rules:
    avoid_setters_without_getters: false
    unawaited_futures: false
    always_put_control_body_on_new_line: false
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    file_names: false
    prefer_single_quotes: false
    flutter_style_todos: false
    avoid_classes_with_only_static_members: false
    invalid_assignment: false
    avoid_bool_literals_in_conditional_expressions: false
    avoid_positional_boolean_parameters: false
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    non_constant_identifier_names: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_statements: true