name: onlylive
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.7
  webview_flutter: ^2.0.2
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  font_awesome_flutter: ^9.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  tencent_trtc_cloud: ^1.0.9
  tencent_im_sdk_plugin: ^3.3.8
  crypto: ^3.0.1
  firebase_messaging: ^10.0.4
  firebase_core_platform_interface: ^4.0.1
  firebase_auth: ^3.1.0
  flutter_local_notifications: ^6.0.0
  flutter_flavor: ^3.0.1
  flutter_flavorizr: ^2.0.0
  yaml: ^3.1.0
  callkeep:
    git:
      url: https://github.com/iMarke/callkeep.git
      ref: develop
  uuid: ^3.0.4
  permission_handler: ^8.1.4
  streaming_shared_preferences: ^2.0.0
  cached_network_image: ^3.1.0
  flutter_native_splash: ^1.2.0
  url_launcher: ^6.0.9
  package_info_plus: ^1.0.4
  intl: ^0.17.0
  flutter_email_sender: ^5.0.2
  country_codes: ^2.0.1
  image_gallery_saver: '^1.6.9'
  logger: ^1.1.0
  openapi:
    path: lib/openapi/
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
flutter_native_splash:
    background_image: assets/images/splash.png
    fullscreen: true

# Flavorの設定
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    development:
      app:
        name: "onlylive dev"

      android:
        applicationId: "com.ILEO.onlylive.development"
      ios:
        bundleId: "com.ILEO.onlylive.development"
        firebase:
          config: "ios/firebase/GoogleService-Info-Development.plist"

    production:
      app:
        name: "onlylive"

      android:
        applicationId: "com.ILEO.onlylive"
      ios:
        bundleId: "com.ILEO.onlylive"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: 1.13.0+3
  provider: ^5.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - env/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages