//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars

library openapi.api;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart';
import 'package:intl/intl.dart';
import 'package:meta/meta.dart';

part 'api_client.dart';
part 'api_helper.dart';
part 'api_exception.dart';
part 'auth/authentication.dart';
part 'auth/api_key_auth.dart';
part 'auth/oauth.dart';
part 'auth/http_basic_auth.dart';
part 'auth/http_bearer_auth.dart';

part 'api/auth_service_api.dart';
part 'api/block_service_api.dart';
part 'api/campaign_service_api.dart';
part 'api/contact_service_api.dart';
part 'api/fan_meeting_health_service_api.dart';
part 'api/fan_meeting_service_api.dart';
part 'api/fan_service_api.dart';
part 'api/feature_service_api.dart';
part 'api/follow_service_api.dart';
part 'api/health_service_api.dart';
part 'api/influencer_service_api.dart';
part 'api/message_service_api.dart';
part 'api/point_service_api.dart';
part 'api/reservation_service_api.dart';
part 'api/wallet_service_api.dart';

part 'model/call_to_fan_request_action.dart';
part 'model/campaign_campaign_code_state.dart';
part 'model/error_response.dart';
part 'model/fan_notification_request_segment.dart';
part 'model/gatewayruntime_error.dart';
part 'model/grpc_add_points_request.dart';
part 'model/grpc_add_points_request_num_extension.dart';
part 'model/grpc_add_points_response.dart';
part 'model/grpc_apple_iap_verification_request.dart';
part 'model/grpc_break_down.dart';
part 'model/grpc_call_to_fan_request.dart';
part 'model/grpc_call_transaction.dart';
part 'model/grpc_campaign.dart';
part 'model/grpc_consume_balance_request.dart';
part 'model/grpc_consume_balance_response.dart';
part 'model/grpc_consume_serial_code_request.dart';
part 'model/grpc_count_num_reserved_fan_response.dart';
part 'model/grpc_create_block_request.dart';
part 'model/grpc_create_campaign_response.dart';
part 'model/grpc_create_contact_report_request.dart';
part 'model/grpc_create_fan_meeting_request.dart';
part 'model/grpc_create_fan_meeting_response.dart';
part 'model/grpc_create_follow_request.dart';
part 'model/grpc_create_incentive_response.dart';
part 'model/grpc_create_message_by_influencer_request.dart';
part 'model/grpc_create_message_by_influencer_response.dart';
part 'model/grpc_create_reservation_request.dart';
part 'model/grpc_create_reservation_response.dart';
part 'model/grpc_create_serial_code_response.dart';
part 'model/grpc_delete_fan_request.dart';
part 'model/grpc_empty.dart';
part 'model/grpc_fan.dart';
part 'model/grpc_fan_meeting.dart';
part 'model/grpc_fan_meeting_and_number_of_reservation.dart';
part 'model/grpc_fan_meeting_and_reserved.dart';
part 'model/grpc_fan_meeting_state.dart';
part 'model/grpc_fan_notification_response.dart';
part 'model/grpc_fan_refresh_token_request.dart';
part 'model/grpc_fan_refresh_token_response.dart';
part 'model/grpc_fan_sex.dart';
part 'model/grpc_fan_sign_in_request.dart';
part 'model/grpc_fan_sign_in_response.dart';
part 'model/grpc_fan_sign_up_request.dart';
part 'model/grpc_fan_sign_up_response.dart';
part 'model/grpc_fanmeeting_style.dart';
part 'model/grpc_feature.dart';
part 'model/grpc_genre.dart';
part 'model/grpc_get_billing_by_month_res.dart';
part 'model/grpc_get_call_transaction_response.dart';
part 'model/grpc_get_fan_meeting_response.dart';
part 'model/grpc_get_fan_response.dart';
part 'model/grpc_get_follower_num_by_influencer_uuid_response.dart';
part 'model/grpc_get_have_paid_balance_fan_num_response.dart';
part 'model/grpc_get_influencer_response.dart';
part 'model/grpc_get_num_calls_response.dart';
part 'model/grpc_get_ranking_response.dart';
part 'model/grpc_get_total_nozoki_num_by_fan_meeting_response.dart';
part 'model/grpc_get_unfinished_reservation_by_fan_response.dart';
part 'model/grpc_health_response.dart';
part 'model/grpc_health_status.dart';
part 'model/grpc_incentive_code.dart';
part 'model/grpc_influencer.dart';
part 'model/grpc_influencer_credential.dart';
part 'model/grpc_influencer_refresh_token_request.dart';
part 'model/grpc_influencer_refresh_token_response.dart';
part 'model/grpc_influencer_sex.dart';
part 'model/grpc_influencer_sign_in_request.dart';
part 'model/grpc_influencer_sign_in_response.dart';
part 'model/grpc_influencer_sign_up_request_sex.dart';
part 'model/grpc_influencer_sign_up_response.dart';
part 'model/grpc_is_extension.dart';
part 'model/grpc_joined_room.dart';
part 'model/grpc_list_by_fan_meeting_id_response.dart';
part 'model/grpc_list_call_history_by_fan_meeting_id_response.dart';
part 'model/grpc_list_campaign_by_fan_response.dart';
part 'model/grpc_list_campaign_by_fan_response_message.dart';
part 'model/grpc_list_campaign_by_influencer_response.dart';
part 'model/grpc_list_fan_meetings_by_genre_response.dart';
part 'model/grpc_list_fan_meetings_by_influencer_uuid_response.dart';
part 'model/grpc_list_fan_meetings_by_topic_response.dart';
part 'model/grpc_list_fan_meetings_response.dart';
part 'model/grpc_list_fan_meetings_with_reservation_only_by_influencer_uuid_response.dart';
part 'model/grpc_list_features_response.dart';
part 'model/grpc_list_follows_by_fan_uuid_response.dart';
part 'model/grpc_list_joined_room_by_fan_response.dart';
part 'model/grpc_list_message_by_fan_uuid_response.dart';
part 'model/grpc_list_un_follows_by_fan_uuid_response.dart';
part 'model/grpc_message.dart';
part 'model/grpc_message_type.dart';
part 'model/grpc_num_extension.dart';
part 'model/grpc_option.dart';
part 'model/grpc_ranking_influencer.dart';
part 'model/grpc_reason_cancel_membership.dart';
part 'model/grpc_report_type.dart';
part 'model/grpc_reservation.dart';
part 'model/grpc_reservation_and_fan.dart';
part 'model/grpc_reservation_state.dart';
part 'model/grpc_timestamp.dart';
part 'model/grpc_topic.dart';
part 'model/grpc_update_call_transaction_request.dart';
part 'model/grpc_update_display_name_fan_request.dart';
part 'model/grpc_update_display_name_fan_response.dart';
part 'model/grpc_update_email_fan_request.dart';
part 'model/grpc_update_email_fan_response.dart';
part 'model/grpc_update_fan_meeting_request.dart';
part 'model/grpc_update_fan_request.dart';
part 'model/grpc_update_image_uri_fan_request.dart';
part 'model/grpc_update_image_uri_fan_response.dart';
part 'model/grpc_update_influencer_request.dart';
part 'model/grpc_update_introduction_fan_request.dart';
part 'model/grpc_update_introduction_fan_response.dart';
part 'model/grpc_update_password_fan_request.dart';
part 'model/grpc_update_voip_token_fan_request.dart';
part 'model/grpc_update_voip_token_fan_response.dart';
part 'model/grpc_upload_cheki_request.dart';
part 'model/grpc_upload_fan_image_request.dart';
part 'model/grpc_upload_fan_image_response.dart';
part 'model/grpc_upload_influencer_image_request.dart';
part 'model/grpc_upload_influencer_image_response.dart';
part 'model/grpc_upload_tencent_instant_message_log_by_fan_meeting_request.dart';
part 'model/grpc_upload_tencent_instant_message_log_by_reservation_request.dart';
part 'model/grpc_upload_tencent_lite_av_log_by_fan_meeting_request.dart';
part 'model/grpc_upload_tencent_lite_av_log_by_reservation_request.dart';
part 'model/grpc_user_type.dart';
part 'model/grpc_wallet.dart';
part 'model/list_by_fan_meeting_id_response_result.dart';
part 'model/list_joined_room_by_fan_response_room.dart';
part 'model/protobuf_any.dart';


const _delimiters = {'csv': ',', 'ssv': ' ', 'tsv': '\t', 'pipes': '|'};
const _dateEpochMarker = 'epoch';
final _dateFormatter = DateFormat('yyyy-MM-dd');
final _regList = RegExp(r'^List<(.*)>$');
final _regSet = RegExp(r'^Set<(.*)>$');
final _regMap = RegExp(r'^Map<String,(.*)>$');

ApiClient defaultApiClient = ApiClient();
